### ISSUE TITLE
How can I read files from folder paths.

### ISSUE THREAD

**Issue by cephaschapa** [FabrizioSandri/r-integration#11]
Hey! I'd like to know how i can read files for example a csv file.

**Comment by FabrizioSandri** [comment]
You can read CSV files from a RScript by using the `read.csv()` function, provided by R.

For example you can create a R script like the following
```
example <- read.csv(file = 'data/example.csv')
```
and then execute this external script from your node js environment as explained [here](https://github.com/FabrizioSandri/r-integration#run-an-external-script)

**Comment by cephaschapa** [comment]
Awesome thanks definitely trying that. Thanks 👌
