### ISSUE TITLE
Error in sending json data from nodejs to r using r-integration

### ISSUE THREAD

**Issue by samyuktha0203** [FabrizioSandri/r-integration#12]
Hello,
I'm currently using NodeJS and integrating R as an npm. 
I'm trying to send this sample json
var jsonobj={"month": "january", "totalrevenue": 1000000}  
to R by R.callMethod. 
In R.file,
 library(rjson) 
library(plyr) 
x = function(data)
 { sample <- rjson::fromJSON(data) 
return (ex) 
} 
where data is the jsonobj.
The function just returns the JSON data as a complete string as supposed to how it is. Given below is how the output is in nodejs.
[ '{month:august,totalrevenue:78841814.37}' ]
The code gives me the following error
Error in rjson::fromJSON(data) : not all data was parsed (0 chars were parsed out of a total of 39 chars)
How can i fetch the JSON back from R exactly as it is passed from NodeJS?

**Comment by FabrizioSandri** [comment]
You have 2 possible solutions:
**1.** The first one is to create a function like the following one
```R
x = function(month, totalrevenue) { 
    ...
}
```
and call it from the NodeJS environment by using the  `callMethod` function provided by `r-integration`:
```js
var jsonobj={"month": "january", "totalrevenue": 1000000};
callMethod("script.R", "x", jsonobj);
```

**2.** The second solution is to send the JSON object as a string to the `x` function and then parse it .
```R
x = function(jsonData) { 
    # parse the jsonData string 
}
```
```js
var jsonobj={"month": "january", "totalrevenue": 1000000};
callMethod("script.R", "x", JSON.stringify(jsonobj));
```
