### ISSUE TITLE
My server gets busy and not respond on endpoints when executing a 3 minutes long R script

### ISSUE THREAD

**Issue by pabloat81** [FabrizioSandri/r-integration#14]
Hi, i am using nest, bull queues and r-integration.

I excecute the R script on a Bull queue, but when excecuting the server gets busy.

When running RScript on a queue, my endpoints do not respond till R finish the job.

There is a way to run non blocking R script or the only way is to make a microservice?

Thanks

**Comment by pabloat81** [comment]
There is a way to use exec async function with await to call the R script? I see you make a new promise an run the sync version but the nodejs server gets blocked

**Comment by FabrizioSandri** [comment]
As you correctly pointed out, the issue was related to the use of `child_process.execSync` inside an asynchronous function. I resolved the issue with release v2.4.0; please let me know whether the issue has been fixed on your server.

**Comment by pabloat81** [comment]
Hi, its appears to be working well now! I will be testing more complex scenarios this week.

Thanks!

**Comment by FabrizioSandri** [comment]
Great, thank you for reporting this!
