### ISSUE TITLE
Passing Strings as Argument

### ISSUE THREAD

**Issue by jakobdanel** [FabrizioSandri/r-integration#3]
Hello,
we want to pass a date formatted in a String "YYYY-MM-DD/YYYY-MM-DD". The problem we had is that R interprates this as a Term and calculates an floating point number from there. Is this a bug or are we missing a way to tell r-integration that we would like to pass a String?

Thank you for your help!

**Comment by FabrizioSandri** [comment]
Thanks for the report, It was a string issue. 

To solve it update to the version 1.4.0 by executing
`npm install r-integration`

**Comment by jakobdanel** [comment]
Thanks for the quick response,
I build also a workaround for the issue, but yours is much smoother than mine.
