### ISSUE TITLE
`callStandardMethod()` to call R's `log()` throws an error

### ISSUE THREAD

**Issue by emmansh** [FabrizioSandri/r-integration#7]
I'm trying to use `R.callStandardMethod()` with R's `log()` function, but so far unsuccessfully. 

```javascript
// in node.js

const R = require('r-integration');
const myArray = [2, 4, 6, 10, 30];
let result = R.callStandardMethod("log", myArray);
console.log(result)
```
Output:
> [R: compile error] Error: Command failed: "C:\Program Files\R\R-4.1.2\bin\Rscript.exe" -e "print(log(2,4,6,10,30))"
> Error in log(2, 4, 6, 10, 30) : unused arguments (6, 10, 30)
> Calls: print
> Execution halted
> 
> 0

Whereas the _expected_ output would be what we get when doing in R:
``` r
my_vec <- c(2, 4, 6, 10, 30)
log(my_vec)
#> [1] 0.6931472 1.3862944 1.7917595 2.3025851 3.4011974
```

Does this have to do with the `log()` being a vectorized function?

**Comment by emmansh** [comment]
I guess it has to do with how a function's input is defined: as dot-dot-dot or named argument.
For example, `max()` accepts its input via `...` but `log()` expects a numeric vector `x`.

One way to test for a function's main input definition is like that:
``` r
is_main_input_ddd <- function(.f) {
  names(formals(args(.f)))[1] == "..."
}

is_main_input_ddd(max)
#> [1] TRUE
is_main_input_ddd(log)
#> [1] FALSE
```

<sup>Created on 2022-01-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by FabrizioSandri** [comment]
I updated to version 1.9.0, check it and let me know if it works.
Thanks

**Comment by emmansh** [comment]
Perfect, thank you!
